# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokeny < Formula
  desc "Minimal TOTP generator from your Shell"
  homepage "https://github.com/zalopay-oss/tokeny"
  version "1.0.2-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2-rc.1/tokeny_1.0.2-rc.1_macOS_x86_64.tar.gz"
      sha256 "c47af234580632d419f56d196f0fdb2c947ba28d17ed925c52759e9ba3da71a0"

      def install
        bin.install "tokeny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2-rc.1/tokeny_1.0.2-rc.1_macOS_arm64.tar.gz"
      sha256 "3cf0ec0339839966c97ba7f7706692b8b59c87e961e3ebc8962e84eeaa5d69fa"

      def install
        bin.install "tokeny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2-rc.1/tokeny_1.0.2-rc.1_Linux_x86_64.tar.gz"
      sha256 "c70503a3f5a9525236407923406f69c3f9d63082db7b7dad6f1d506edbfde581"

      def install
        bin.install "tokeny"
      end
    end
  end
end
