# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokeny < Formula
  desc "Minimal TOTP generator from your Shell"
  homepage "https://github.com/zalopay-oss/tokeny"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2/tokeny_1.0.2_macOS_arm64.tar.gz"
      sha256 "df075aafc1d34729939dab862751023cf3ee021c44e74be144cece3e5ae0f2ad"

      def install
        bin.install "tokeny"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2/tokeny_1.0.2_macOS_x86_64.tar.gz"
      sha256 "2a484594efcc35b8310d7e7107f8786b24943640449be240d974a839dac9e3a8"

      def install
        bin.install "tokeny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zalopay-oss/tokeny/releases/download/v1.0.2/tokeny_1.0.2_Linux_x86_64.tar.gz"
      sha256 "1291c76d591c610502dc82d9bead3cbb8c6f759d0f13e826f53e501d0053fc64"

      def install
        bin.install "tokeny"
      end
    end
  end
end
